[build]
buildCommand = "python manage.py collectstatic --noinput"

[deploy]
releaseCommand = "python manage.py migrate"
startCommand = "gunicorn ecommerce_assistant.wsgi:application --bind 0.0.0.0:$PORT"
