# Generated by Django 5.2 on 2025-04-21 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_conversation_chatmessage_conversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='persona',
            field=models.CharField(blank=True, choices=[('budget', 'Budget Buyer'), ('luxury', 'Luxury Seeker'), ('eco', 'Eco‑Conscious'), ('tech', 'Tech Enthusiast'), ('casual', 'Casual Shopper')], help_text='Snapshot of the user’s persona when the chat started', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='persona',
            field=models.CharField(blank=True, choices=[('budget', 'Budget Buyer'), ('luxury', 'Luxury Seeker'), ('eco', 'Eco‑Conscious'), ('tech', 'Tech Enthusiast'), ('casual', 'Casual Shopper')], max_length=20),
        ),
    ]
